# Autogenerated wrapper script for TOPCOM_jll for armv7l-linux-musleabihf-cxx03
export chiro2allfinetriangs, chiro2alltriangs, chiro2circuits, chiro2cocircuits, chiro2dual, chiro2finetriang, chiro2finetriangs, chiro2mintriang, chiro2nallfinetriangs, chiro2nalltriangs, chiro2nfinetriangs, chiro2ntriangs, chiro2placingtriang, chiro2triangs, cocircuits2facets, points2allfinetriangs, points2alltriangs, points2chiro, points2facets, points2finetriang, points2finetriangs, points2flips, points2nallfinetriangs, points2nalltriangs, points2nfinetriangs, points2nflips, points2ntriangs, points2placingtriang, points2triangs, points2volume, santos_22_triang, santos_dim4_triang, santos_triang

using GMP_jll
using cddlib_jll
JLLWrappers.@generate_wrapper_header("TOPCOM")
JLLWrappers.@declare_executable_product(chiro2allfinetriangs)
JLLWrappers.@declare_executable_product(chiro2alltriangs)
JLLWrappers.@declare_executable_product(chiro2circuits)
JLLWrappers.@declare_executable_product(chiro2cocircuits)
JLLWrappers.@declare_executable_product(chiro2dual)
JLLWrappers.@declare_executable_product(chiro2finetriang)
JLLWrappers.@declare_executable_product(chiro2finetriangs)
JLLWrappers.@declare_executable_product(chiro2mintriang)
JLLWrappers.@declare_executable_product(chiro2nallfinetriangs)
JLLWrappers.@declare_executable_product(chiro2nalltriangs)
JLLWrappers.@declare_executable_product(chiro2nfinetriangs)
JLLWrappers.@declare_executable_product(chiro2ntriangs)
JLLWrappers.@declare_executable_product(chiro2placingtriang)
JLLWrappers.@declare_executable_product(chiro2triangs)
JLLWrappers.@declare_executable_product(cocircuits2facets)
JLLWrappers.@declare_executable_product(points2allfinetriangs)
JLLWrappers.@declare_executable_product(points2alltriangs)
JLLWrappers.@declare_executable_product(points2chiro)
JLLWrappers.@declare_executable_product(points2facets)
JLLWrappers.@declare_executable_product(points2finetriang)
JLLWrappers.@declare_executable_product(points2finetriangs)
JLLWrappers.@declare_executable_product(points2flips)
JLLWrappers.@declare_executable_product(points2nallfinetriangs)
JLLWrappers.@declare_executable_product(points2nalltriangs)
JLLWrappers.@declare_executable_product(points2nfinetriangs)
JLLWrappers.@declare_executable_product(points2nflips)
JLLWrappers.@declare_executable_product(points2ntriangs)
JLLWrappers.@declare_executable_product(points2placingtriang)
JLLWrappers.@declare_executable_product(points2triangs)
JLLWrappers.@declare_executable_product(points2volume)
JLLWrappers.@declare_executable_product(santos_22_triang)
JLLWrappers.@declare_executable_product(santos_dim4_triang)
JLLWrappers.@declare_executable_product(santos_triang)
function __init__()
    JLLWrappers.@generate_init_header(GMP_jll, cddlib_jll)
    JLLWrappers.@init_executable_product(
        chiro2allfinetriangs,
        "bin/chiro2allfinetriangs",
    )

    JLLWrappers.@init_executable_product(
        chiro2alltriangs,
        "bin/chiro2alltriangs",
    )

    JLLWrappers.@init_executable_product(
        chiro2circuits,
        "bin/chiro2circuits",
    )

    JLLWrappers.@init_executable_product(
        chiro2cocircuits,
        "bin/chiro2cocircuits",
    )

    JLLWrappers.@init_executable_product(
        chiro2dual,
        "bin/chiro2dual",
    )

    JLLWrappers.@init_executable_product(
        chiro2finetriang,
        "bin/chiro2finetriang",
    )

    JLLWrappers.@init_executable_product(
        chiro2finetriangs,
        "bin/chiro2finetriangs",
    )

    JLLWrappers.@init_executable_product(
        chiro2mintriang,
        "bin/chiro2mintriang",
    )

    JLLWrappers.@init_executable_product(
        chiro2nallfinetriangs,
        "bin/chiro2nallfinetriangs",
    )

    JLLWrappers.@init_executable_product(
        chiro2nalltriangs,
        "bin/chiro2nalltriangs",
    )

    JLLWrappers.@init_executable_product(
        chiro2nfinetriangs,
        "bin/chiro2nfinetriangs",
    )

    JLLWrappers.@init_executable_product(
        chiro2ntriangs,
        "bin/chiro2ntriangs",
    )

    JLLWrappers.@init_executable_product(
        chiro2placingtriang,
        "bin/chiro2placingtriang",
    )

    JLLWrappers.@init_executable_product(
        chiro2triangs,
        "bin/chiro2triangs",
    )

    JLLWrappers.@init_executable_product(
        cocircuits2facets,
        "bin/cocircuits2facets",
    )

    JLLWrappers.@init_executable_product(
        points2allfinetriangs,
        "bin/points2allfinetriangs",
    )

    JLLWrappers.@init_executable_product(
        points2alltriangs,
        "bin/points2alltriangs",
    )

    JLLWrappers.@init_executable_product(
        points2chiro,
        "bin/points2chiro",
    )

    JLLWrappers.@init_executable_product(
        points2facets,
        "bin/points2facets",
    )

    JLLWrappers.@init_executable_product(
        points2finetriang,
        "bin/points2finetriang",
    )

    JLLWrappers.@init_executable_product(
        points2finetriangs,
        "bin/points2finetriangs",
    )

    JLLWrappers.@init_executable_product(
        points2flips,
        "bin/points2flips",
    )

    JLLWrappers.@init_executable_product(
        points2nallfinetriangs,
        "bin/points2nallfinetriangs",
    )

    JLLWrappers.@init_executable_product(
        points2nalltriangs,
        "bin/points2nalltriangs",
    )

    JLLWrappers.@init_executable_product(
        points2nfinetriangs,
        "bin/points2nfinetriangs",
    )

    JLLWrappers.@init_executable_product(
        points2nflips,
        "bin/points2nflips",
    )

    JLLWrappers.@init_executable_product(
        points2ntriangs,
        "bin/points2ntriangs",
    )

    JLLWrappers.@init_executable_product(
        points2placingtriang,
        "bin/points2placingtriang",
    )

    JLLWrappers.@init_executable_product(
        points2triangs,
        "bin/points2triangs",
    )

    JLLWrappers.@init_executable_product(
        points2volume,
        "bin/points2volume",
    )

    JLLWrappers.@init_executable_product(
        santos_22_triang,
        "bin/santos_22_triang",
    )

    JLLWrappers.@init_executable_product(
        santos_dim4_triang,
        "bin/santos_dim4_triang",
    )

    JLLWrappers.@init_executable_product(
        santos_triang,
        "bin/santos_triang",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
